import { ApplicationStatus, LaunchStatus, LeadStatus } from "@prisma/client";
import { prisma } from "@/server/db/client";
import { compareCampaigns, summarizeCampaignFunnel, type CampaignComparisonEntry } from "@/server/services/feedback-service";

// Phase 4E: composes the already-existing Stage 10/Stage 11 aggregation
// (compareCampaigns(), which itself reuses getCampaignPerformance() per
// campaign — see feedback-service.ts) with a small number of new,
// deterministic, read-only queries that genuinely don't exist anywhere
// else in the codebase yet: the three "Attention Required" conditions and
// a recent-ActivityLog read. Nothing here writes, nothing here duplicates
// a calculation that already exists elsewhere.

export type DashboardKpis = {
  totalLeads: number;
  totalApplications: number;
  wonSales: number;
  totalSalesValue: string;
  winRate: number;
};

// `rate` is the conversion rate from the PREVIOUS stage into this one —
// absent for the first stage, and deliberately null (not 0) for Clicks
// (Ads -> Clicks has no rate: this system never captures ad-impression/
// reach data, so a click-through rate can't be legitimately computed —
// same reasoning as campaign-performance-service.ts's own
// FunnelConversionRates). Populated from summarizeCampaignFunnel()'s own
// already-computed rate fields — never a new calculation.
export type FunnelStage = { key: string; label: string; count: number; rate?: number | null };

export type AttentionItem = {
  id: string;
  message: string;
  href: string;
};

export type RecentActivityItem = {
  id: string;
  label: string;
  contextLabel: string;
  contextHref: string | null;
  actorType: string;
  createdAt: string;
};

export type DashboardOverview = {
  kpis: DashboardKpis;
  funnel: FunnelStage[];
  campaigns: CampaignComparisonEntry[];
  attention: {
    zeroClickCampaigns: AttentionItem[];
    hotLeadsWithoutHandover: AttentionItem[];
    submittedWithoutSale: AttentionItem[];
  };
  recentActivity: RecentActivityItem[];
};

const RECENT_ACTIVITY_LIMIT = 20;
const ATTENTION_LIMIT = 8;

// "Launched" means an actual live Launch row (LaunchStatus.live) — not
// merely a Launch existing (pending/launching/failed/cancelled rows don't
// count as "launched"). Cross-referenced against totalClicks already
// computed per campaign by compareCampaigns() — no extra click query.
async function getZeroClickLiveCampaigns(campaigns: CampaignComparisonEntry[]): Promise<AttentionItem[]> {
  const liveLaunches = await prisma.launch.findMany({
    where: { status: LaunchStatus.live },
    select: { campaignId: true },
    distinct: ["campaignId"],
  });
  const liveCampaignIds = new Set(liveLaunches.map((l) => l.campaignId));

  return campaigns
    .filter((c) => liveCampaignIds.has(c.campaignId) && c.totalClicks === 0)
    .slice(0, ATTENTION_LIMIT)
    .map((c) => ({
      id: c.campaignId,
      message: `"${c.campaignName}" is live but has recorded zero clicks.`,
      href: `/campaigns/${c.campaignId}/performance`,
    }));
}

async function getHotLeadsWithoutHandover(): Promise<AttentionItem[]> {
  const leads = await prisma.lead.findMany({
    where: { status: LeadStatus.hot, handoverAt: null },
    include: { campaign: { select: { name: true } } },
    orderBy: { updatedAt: "desc" },
    take: ATTENTION_LIMIT,
  });

  return leads.map((lead) => ({
    id: lead.id,
    message: `${lead.name || lead.phone} (${lead.campaign.name}) is hot but hasn't been handed over.`,
    href: `/leads/${lead.id}`,
  }));
}

async function getSubmittedWithoutSale(): Promise<AttentionItem[]> {
  const leads = await prisma.lead.findMany({
    where: { applicationStatus: ApplicationStatus.submitted, sale: null },
    include: { campaign: { select: { name: true } } },
    orderBy: { updatedAt: "desc" },
    take: ATTENTION_LIMIT,
  });

  return leads.map((lead) => ({
    id: lead.id,
    message: `${lead.name || lead.phone} (${lead.campaign.name}) submitted an application with no sale outcome yet.`,
    href: `/leads/${lead.id}`,
  }));
}

const ACTIVITY_LABELS: Record<string, string> = {
  created: "Campaign created",
  basics_updated: "Campaign basics updated",
  differentiators_updated: "Differentiators updated",
  datasets_selected: "Datasets selected",
  buildings_selected: "Buildings selected",
  confirmed: "Campaign confirmed",
  imported: "Dataset imported",
  ai_strategy_generated: "Marketing strategy generated by AI",
  ai_strategy_generation_failed: "AI strategy generation failed",
  strategy_edited: "Marketing strategy edited",
  strategy_approved: "Marketing strategy approved",
  content_generated: "Content generated by AI",
  content_generation_failed: "AI content generation failed",
  content_edited: "Content edited",
  content_approved: "Content approved",
  launch_requested: "Launch requested",
  launch_succeeded: "Launch succeeded",
  launch_failed: "Launch failed",
  acquisition_event_recorded: "Ad click recorded",
  lead_created: "New lead created",
  lead_customer_info_updated: "Customer info updated by AI",
  lead_classified: "Lead classified",
  lead_status_changed: "Lead status changed",
  lead_handed_over: "Lead handed over to an agent",
  application_status_changed: "Application status changed",
  follow_up_created: "Follow-up journey started",
  follow_up_cancelled: "Follow-up cancelled",
  follow_up_sent: "Follow-up sent",
  follow_up_send_failed: "Follow-up send failed",
  whatsapp_message_received: "WhatsApp message received",
  whatsapp_message_sent: "WhatsApp message sent",
  whatsapp_message_send_failed: "WhatsApp message send failed",
  ai_response_generated: "AI response generated",
  sale_recorded: "Sale outcome recorded",
  sale_updated: "Sale outcome updated",
};

const ENTITY_LABELS: Record<string, string> = {
  campaign: "Campaign",
  lead: "Lead",
  sale: "Sale",
  follow_up: "Follow-up",
  content_set: "Content",
  marketing_strategy: "Strategy",
  launch: "Launch",
  dataset: "Dataset",
  whatsapp_message: "WhatsApp message",
  acquisition_event: "Ad click",
};

// Resolves entityId -> a real name only for the two entity types that have
// one worth showing (campaign name, lead name/phone) — a genuine lookup
// against the id already stored on the row, never a guess. Every other
// entityType falls back to its humanized type label with no link, rather
// than fabricating a name.
async function buildRecentActivity(): Promise<RecentActivityItem[]> {
  const rows = await prisma.activityLog.findMany({
    orderBy: { createdAt: "desc" },
    take: RECENT_ACTIVITY_LIMIT,
  });

  const campaignIds = [...new Set(rows.filter((r) => r.entityType === "campaign").map((r) => r.entityId))];
  const leadIds = [...new Set(rows.filter((r) => r.entityType === "lead").map((r) => r.entityId))];

  const [campaigns, leads] = await Promise.all([
    campaignIds.length > 0
      ? prisma.campaign.findMany({ where: { id: { in: campaignIds } }, select: { id: true, name: true } })
      : Promise.resolve([]),
    leadIds.length > 0
      ? prisma.lead.findMany({ where: { id: { in: leadIds } }, select: { id: true, name: true, phone: true } })
      : Promise.resolve([]),
  ]);
  const campaignById = new Map(campaigns.map((c) => [c.id, c]));
  const leadById = new Map(leads.map((l) => [l.id, l]));

  return rows.map((row) => {
    let contextLabel = ENTITY_LABELS[row.entityType] ?? row.entityType.replace(/_/g, " ");
    let contextHref: string | null = null;

    if (row.entityType === "campaign") {
      const campaign = campaignById.get(row.entityId);
      if (campaign) {
        contextLabel = campaign.name;
        contextHref = `/campaigns/${campaign.id}/brief`;
      }
    } else if (row.entityType === "lead") {
      const lead = leadById.get(row.entityId);
      if (lead) {
        contextLabel = lead.name || lead.phone;
        contextHref = `/leads/${lead.id}`;
      }
    }

    return {
      id: row.id,
      label: ACTIVITY_LABELS[row.action] ?? row.action.replace(/_/g, " "),
      contextLabel,
      contextHref,
      actorType: row.actorType,
      createdAt: row.createdAt.toISOString(),
    };
  });
}

export async function getDashboardOverview(): Promise<DashboardOverview> {
  const { campaigns } = await compareCampaigns();
  const totals = summarizeCampaignFunnel(campaigns);

  const kpis: DashboardKpis = {
    totalLeads: totals.totalLeads,
    totalApplications: totals.totalApplications,
    wonSales: totals.wonSales,
    totalSalesValue: totals.totalSalesValue,
    winRate: totals.winRate,
  };

  const funnel: FunnelStage[] = [
    { key: "ads", label: "Ads", count: totals.totalAds },
    { key: "clicks", label: "Clicks", count: totals.totalClicks, rate: null },
    { key: "enquiries", label: "WhatsApp Enquiries", count: totals.totalWhatsAppEnquiries, rate: totals.clickToEnquiryRate },
    { key: "applications", label: "Applications", count: totals.totalApplications, rate: totals.enquiryToApplicationRate },
    { key: "qualified", label: "Qualified", count: totals.totalQualifiedLeads, rate: totals.applicationToQualifiedRate },
    { key: "sales", label: "Sales", count: totals.totalSales, rate: totals.qualifiedToSaleRate },
  ];

  const [zeroClickCampaigns, hotLeadsWithoutHandover, submittedWithoutSale, recentActivity] = await Promise.all([
    getZeroClickLiveCampaigns(campaigns),
    getHotLeadsWithoutHandover(),
    getSubmittedWithoutSale(),
    buildRecentActivity(),
  ]);

  return {
    kpis,
    funnel,
    campaigns,
    attention: { zeroClickCampaigns, hotLeadsWithoutHandover, submittedWithoutSale },
    recentActivity,
  };
}
